insert into baite(nome,postiLetto, link, note)values
("Casa per Ferie La Benevola", 64,"https://ospitalitareligiosa.it/strutture/ad/casa-la-benevola,4144","Occupata"),
("Casa vacanze il nido",42,"https://www.grupix.it/casa-vacanza/1046/il-nido/","Occupata"),
("Colonia Alpina di Gardolo",59,"https://ospitalitareligiosa.it/strutture/ad/gardolo,4151",""),
("Circolo San Luca",100,"https://www.casaferie.it/","Pensione completa, no affitto"),
("Casa per ferie Belvedere",38,"https://www.circolonoimirano.com/casa-belvedere","Occupata"),
("Casa per ferie Don Martino del Lugan", 55, "http://www.parrocchieprimierovanoi.it/casa-per-ferie-martino-de-lugan/", "Richiesto un minimo garantito proporzionale al numero di posti letto, Motivo soggiorno Campi scuola, Ritiri spirituali, Incontri di preghiera, Colonie, Settimane bianche"),
("Maso Bosato", 40, "https://www.caseinautogestione.it/it/m-dettaglio-casa.php?hid=310&srctesto=Cerca+la+tua+casa&srcreg=17&srcprov=93&srcplac=30&arrival=30-12-2025&departure=01-01-2026", "chiuso a capodanno"),
("Maso Regolo",60,"https://www.masoregolo.it/?mese=12&anno=2025#cal-date_occupate_inverno-1","Occupato"),
("Cà Del Tiglio Srls",82,"https://www.cadeltiglio.it/",""),
("Foresteria Miramonti",91,"https://www.foresteriamiramontitn.it/","Da capire, struttura particolare"),
("Residenza Cernuschese Madonna del Lares",74,"https://www.orizzontegiovani.it/area-ospitalita/casa-madonna-del-lares/","Segnata come momentaneamente chiusa"),
("Casa Arlecchino",68,"https://www.orizzontegiovani.it/area-ospitalita/casa-arlecchino/",""),
("College la collina",80,"https://www.orizzontegiovani.it/area-ospitalita/college-la-collina/","sarebbe il top"),
("Casa Terre Comuni",10,"Casa Terre Comuni",""),
("Baita Sperandio Casa Vacanze in Tesino",30,"https://www.baitasperandio.it/",""),
("Casa a Lutago", 50, "https://www.socialholiday.eu/portfolio-view/casa-a-lutago-bz-rif-469/",""),
("Casa per ferie Seandre",70,"https://www.caseinautogestione.it/it/m-dettaglio-casa.php?hid=696",""),
("Casa in autogestione a Vermiglio",40,"https://www.socialholiday.eu/portfolio-view/casa-in-autogestione-a-vermiglio-rif-186/",""),
("Piz Meda",45,"https://www.pizmeda.it/",""),
("Dal Trozzo",60,"https://www.turismosocialetrentino.it/casa-dal-trozzo/",""),
("Don Santo Amistadi",25,"https://www.turismosocialetrentino.it/casadonsanto/",""),
("Brione",22,"https://www.turismosocialetrentino.it/casa-brione/",""),
("Cif",50,"https://www.turismosocialetrentino.it/casa-cif/",""),
("Magnola",55,"https://www.turismosocialetrentino.it/casa-magnola/",""),
("Folserhof",70,"https://www.caseinautogestione.it/it/m-dettaglio-casa.php?hid=273","(sono crucchi)"),
("Learning Resort Castelbasso",40,"https://www.castelbasso.com/",""),
("Celentino",55,"https://www.caseinautogestione.it/it/m-dettaglio-casa.php?hid=82&srctesto=Cerca+la+tua+casa&srcreg=17&srcprov=93&srcplac=30&arrival=30-12-2025&departure=01-01-2026",""),
("Villa Sacro Cuore",50,"http://www.villasacrocuore.net/index.html","Disponibilità sul loro sito Modulo per prenotare sul loro sito POSTI LETTO VARIABILI 50/80/25/16"),
("Casa Limes Valdaone",50,"https://www.caseinautogestione.it/it/m-dettaglio-casa.php?hid=1286","3500 sono un bel po di schei per 35 persone"),
("Casa vacanze per gruppi javrè",56,"https://www.caseinautogestione.it/it/m-dettaglio-casa.php?hid=676",""),
("Primalunetta", 34,"https://archivio-castelivano.openpa.opencontent.io/Aree-tematiche/Turismo/Casa-Vacanze-Gruppi-Primalunetta","60 posti se ci sono le tende"),
("Casa incontri",35,"https://www.caseinautogestione.it/it/m-dettaglio-casa.php?hid=149",""),
("Casa parrocchiale S. Caterina Monclassico",50,"https://www.caseinautogestione.it/it/m-dettaglio-casa.php?hid=947","Solo a gruppi parrochiali "),
("Baita don Bosco",44,"https://www.caseinautogestione.it/it/m-dettaglio-casa.php?hid=604&srctesto=Cerca+la+tua+casa&srcreg=17&srcprov=93&srcplac=30&arrival=30-12-2025&departure=01-01-2026",""),
("San giovanni al monte", 45,"https://www.oratorioarco.it/colonia/",""),
("Baita pravec",40,"https://www.associazionespaziogiovani.it/baita-pravec/",""),
("Casa Alpina don Vigilio Flabbi di Faserno",250,"https://www.coloniafaserno.it/wp/struttura/","POSTI LETTO DA RIVEDERE ASSOLUTAMENTE"),
("Villa santi", 30 , "https://www.pnab.it/poi/villa-santi/",""),
("Restor Natura Malga Mondent",30, "https://area.events/item/restor-natura-malga-mondent/","");

